config/routes.rb
RestSite::Application.routes.draw do
  

  resources :entrees #, except: [:index]

  resources :orders

  get '/menu', to: 'entrees#index'

   root 'welcome#index'

end

app/models/entree.rb
class Entree < ActiveRecord::Base

	has_many :tickets
	has_many :customers, through: :tickets
end

app/models/order.rb
class Order < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/entrees_controller.rb
class EntreesController < ApplicationController
  before_action :set_entree, only: [:show, :edit, :update, :destroy]

  # GET /entrees
  # GET /entrees.json
  def index
    @entrees = Entree.all
  end

  # GET /entrees/1
  # GET /entrees/1.json
  def show
  end

  # GET /entrees/new
  def new
    @entree = Entree.new
  end

  # GET /entrees/1/edit
  def edit
  end

  # POST /entrees
  # POST /entrees.json
  def create
    @entree = Entree.new(entree_params)
    respond_to do |format|
      if @entree.save
        format.html { redirect_to @entree, notice: 'Entree was successfully created.' }
        format.json { render action: 'show', status: :created, location: @entree }
      else
        format.html { render action: 'new' }
        format.json { render json: @entree.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entrees/1
  # PATCH/PUT /entrees/1.json
  def update
    respond_to do |format|
      if @entree.update(entree_params)
        format.html { redirect_to @entree, notice: 'Entree was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @entree.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entrees/1
  # DELETE /entrees/1.json
  def destroy
    @entree.destroy
    respond_to do |format|
      format.html { redirect_to entrees_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entree
      @entree = Entree.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entree_params
      params.require(:entree).permit(:item, :description, :price)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	#before_action :set_order, only: [:show, :edit, :update, :destroy]

	def index
		@orders = Order.all
	end

	def show
	end

	def new
		@order = Order.new
	end

	def edit
	end

	def create
		@order = Order.new(order_params)
		respond_to do |format|
			if @order.save
				format.html  {redirect_to @order, notice: 'Order was created successfully'}
			else
				format.html {redirect_to @order, action: 'new'}
			end
		end
	end

	def update
		@order = Order.edit(order_params)
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entrees_helper.rb
module EntreesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/entrees/_form.html.erb
<%= form_for(@entree) do |f| %>
  <% if @entree.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entree.errors.count, "error") %> prohibited this entree from being saved:</h2>

      <ul>
      <% @entree.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :item %><br>
    <%= f.text_field :item %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>

  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price, :class => 'text_field', :step => 'any' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entrees/edit.html.erb
<h1>Editing entree</h1>

<%= render 'form' %>

<%= link_to 'Show', @entree %> |
<%= link_to 'Back', entrees_path %>

app/views/entrees/index.html.erb
<h1>Menu</h1>

<table>
  <thead>
    <tr>
      <th>Item</th>
      <th>Description</th>
      <th>Price</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @entrees.each do |entree| %>
      <tr>
        <td><%= entree.item %></td>
        <td><%= entree.description %></td>
        <td><%= entree.price %></td>
        <td><%= link_to 'Show', entree %></td>
        <td><%= link_to 'Edit', edit_entree_path(entree) %></td>
        <td><%= link_to 'Destroy', entree, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Entree', new_entree_path %>

app/views/entrees/new.html.erb
<h1>New entree</h1>

<%= render 'form' %>

<%= link_to 'Back', entrees_path %>

app/views/entrees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item:</strong>
  <%= @entree.item %>
</p>

<p>
  <strong>Description:</strong>
  <%= @entree.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @entree.price %>
</p>

<%= link_to 'Edit', edit_entree_path(@entree) %> |
<%= link_to 'Back', entrees_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RestSite</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :full_name %><br>
    <%= f.text_field :full_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_area :email %>

  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.telephone_field :phone_number %>
  </div>

  <div class="field">
    <%= f.label :address_line_1 %><br>
    <%= f.text_field :address_line_1 %>
  </div>

  <div class="field">
    <%= f.label :address_line_2 %><br>
    <%= f.text_field :address_line_2 %>
  </div>

  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>

  <div class="field">
    <%= f.label :zip_code %><br>
    <%= f.number_field :zip_code %>
  </div>

  <div class="field">
    <%= f.label :order_type %><br>
    <%= f.select :pick_up, [["Pick Up", true], ["Delivery", false]] %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/orders/edit.html.erb
<h1> Editing Orders <h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Full Name</th>
      <th>Email</th>
      <th>Phone Number</th>
      <th>Address Line 1</th>
      <th>Address Line 2</th>
      <th>City</th>
      <th>State</th>
      <th>Zip Code</th>
      <th>Order Type</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.full_name %></td>
        <td><%= order.email %></td>
        <td><%= order.phone_number %></td>
        <td><%= order.address_line_1 %></td>
        <td><%= order.address_line_2 %></td>
        <td><%= order.city %></td>
        <td><%= order.state %></td>
        <td><%= order.zip_code %></td>
        <td><%= order.order_type %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Full Name:</strong>
  <%= @order.full_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @order.email %>
</p>

<p>
  <strong>Phone Number:</strong>
  <%= @order.phone_number %>
</p>

<p>
  <strong>Address Line 1:</strong>
  <%= @order.address_line_1 %>
</p>

<p>
  <strong>Address Line 2:</strong>
  <%= @order.address_line_2 %>
</p>

<p>
  <strong>City:</strong>
  <%= @order.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @order.state %>
</p>

<p>
  <strong>Zip Code:</strong>
  <%= @order.zip_code %>
</p>

<p>
  <strong>Order Type:</strong>
  <%= @order.order_type %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/welcome/index.html.erb
<div>
	<h1> Hello World! <br> <br>
	This is the Restaurant Home Page!  </h1>
</div>

<td><%= link_to 'Menu', menu_path %></td>